  
version: 2.1
jobs:
  build:
    working_directory: ~/TestRepository
    docker:
      - image: circleci/python:3.6.6  

    steps:
      - checkout
      - run: # install and activate virtual environment with pip
           name: install dependencies
           command: |
             python3 -m venv venv
             . venv/bin/activate
             pip install -r requirements.txt
             jupyter-nbconvert --execute ./Homework1.ipynb


      - store_artifacts:
          path: ./Homework1.ipynb
          destination: JupyterToHTML
