  
version: 2.1
jobs:
  build:
    working_directory: ~/TestRepository
    docker:
      - image: circleci/python:3.6.6  

    steps:
      - checkout
      - run: 
           command: |
             python3 -m venv venv
             . venv/bin/activate
             pip install -r requirements.txt
             jupyter-nbconvert --execute ./Homework1.ipynb

           
      - run: 
          command: |
            . venv/bin/activate
             export KAGGLE_KEY
             export KAGGLE_LOGIN 
             echo "{"username":\"${KAGGLE_USERNAME}\","key":\"${KAGGLE_KEY}\}" > kaggle.json
             mkdir .kaggle
             mv kaggle.json .kaggle
             kaggle competitions download titanic
             jupyter-nbconvert --execute TitanicNotebook.ipynb
             kaggle competitions submit titanic -f titanic.csv 

      - store_artifacts:
          path: ./Homework1.html
          destination: JupyterToHTML
