  
version: 2.1
jobs:
  build:
    working_directory: ~/TestRepository
    docker:
      - image: circleci/python:3.6.6  

    steps:
      - checkout
      - run: 
           command: |
             python3 -m venv venv
             . venv/bin/activate
             pip install -r requirements.txt
             jupyter-nbconvert --execute ./Homework1.ipynb

           
      - run: 
          command: |
             . venv/bin/activate
             export KAGGLE_KEY
             export KAGGLE_LOGIN 
             mkdir ~/.kaggle
             echo "{\"username\":\"${KAGGLE_LOGIN}\",\"key\":\"${KAGGLE_KEY}\"}" > ~/.kaggle/kaggle.json
             chmod 600 /home/circleci/.kaggle/kaggle.json
             kaggle competitions download titanic
             dir
             zipObj = ZipFile(titanic.zip, 'r')
             zipObj.extractall()
             #jupyter-nbconvert --execute TitanicNotebook.ipynb
             #kaggle competitions submit titanic -f titanic.csv
                      
          paths:
            - "venv"


      - store_artifacts:
          path: ./Homework1.html
          destination: JupyterToHTML



