version: 2.1
jobs:
  build:
    working_directory: ~/TestRepository
    docker:
      - image: python:3.6.3-jessie

    steps:
      - run: # install and activate virtual environment with pip
           name: install dependencies
           command: |
             python3 -m venv venv
             . venv/bin/activate
             pip install -r requirements.txt


      - store_artifacts:
          path: task
          destination: task
